services:
  postgres:
    image: postgres:16
    container_name: postgress_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-learn_backend}
    ports:
      - "5432:5432"
    volumes:
      - ./localdev/data/learn_backend_pgdata:/var/lib/postgresql/data